apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: catprices-app
  labels:
    app: catprices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catprices-app
  template:
    metadata:
      labels:
        app: catprices-app
    spec:
      containers:
        - name: catprices-app
          image: dali/catprices:latest # Mettez à jour avec le chemin de l'image locale
          imagePullPolicy: Never # Indiquez de ne pas essayer de tirer l'image depuis Docker Hub
