apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: catprices-app
  labels:
    app: catprices-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catprices-app
  template:
    metadata:
      labels:
        app: catprices-app
    spec:
      containers:
        - name: catprices-app
          image: dali/catprices:latest
          imagePullPolicy: Always
